// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package client

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// Call provides a mock function with given fields: method, params, result
func (_m *MockClient) Call(method string, params interface{}, result interface{}) error {
	ret := _m.Called(method, params, result)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, interface{}) error); ok {
		r0 = rf(method, params, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CallWithContext provides a mock function with given fields: ctx, method, params, result
func (_m *MockClient) CallWithContext(ctx context.Context, method string, params interface{}, result interface{}) error {
	ret := _m.Called(ctx, method, params, result)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, interface{}) error); ok {
		r0 = rf(ctx, method, params, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
